import Constants from './constants';

export default {
  birdsData: [
    {
      id: '1-2019',
      type: 'Canario',
      notes: 'Alas amarillas, ojos negros.',
      gender: 'Macho',
      photo: Constants.defaultAvatar,
      fatherId: undefined,
      motherId: undefined,
    },
    {
      id: '2-2019',
      type: 'Canario',
      notes: 'Alas verdes, ojos negros.',
      gender: 'Macho',
      photo: Constants.defaultAvatar,
      fatherId: undefined,
      motherId: undefined,
    },
    {
      id: '3-2019',
      type: 'Gorrión',
      gender: 'Hembra',
      photo: Constants.defaultAvatar,
      fatherId: undefined,
      motherId: undefined,
    },
    {
      id: '4-2019',
      type: 'Canario',
      notes: 'Alas amarillas, ojos negros.',
      gender: 'Macho',
      photo: Constants.defaultAvatar,
      fatherId: undefined,
      motherId: undefined,
    },
    {
      id: '5-2019',
      type: 'Canario',
      notes: 'Alas amarillas, ojos negros.',
      gender: 'Hembra',
      photo: Constants.defaultAvatar,
      fatherId: undefined,
      motherId: undefined,
    },
    {
      id: '6-2019',
      type: 'Canario',
      notes: 'Alas amarillas, ojos negros.',
      gender: 'Macho',
      photo: Constants.defaultAvatar,
      fatherId: undefined,
      motherId: undefined,
    },
    {
      id: '7-2019',
      type: 'Verdin',
      notes: 'Alas amarillas, ojos negros.',
      gender: 'Hembra',
      photo: Constants.defaultAvatar,
      fatherId: undefined,
      motherId: undefined,
    },
    {
      id: '8-2019',
      type: 'Canario',
      notes: 'Alas amarillas, ojos marrones.',
      gender: 'Macho',
      photo: Constants.defaultAvatar,
      fatherId: undefined,
      motherId: undefined,
    },
  ],
};
